### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hmans** [hmans/create-react-game#1]
A high-level roadmap of things to do and stuff to add.

### Template

- [x] Bootstrap a Vite app with Three.js, R3f et al
- [ ] Add some macro state structure (loading screen, menu screen, gameplay "screen", pause screen) using a future macro state library
- [ ] Add Input Composer with a sane default configuration
- [ ] Add Shader Composer with a simple example
- [ ] Add VFX Composer with a simple example
- [ ] Add game UI with a sane default configuration
- [ ] Add Miniplex with a sane default configuration (and some example code)
- [ ] Add a sane Postprocessing setup (or similar)

### Install Script

- [x] Implement a basic first `yarn create react-game`
- [ ] Write some basic tests we can throw at GH Actions
- [ ] Ask the user if they want the project to be initialized with Git (instead of forcing it)
- [ ] Ask the user if they want dependencies to be installed (instead of forcing it)
- [ ] Print a final message with some basic instructions on what to do next
